cleanup:
  cleanupCustomResource: false

crds:
  needcreate: true

controller:
  image: registry.aliyuncs.com/acs/kubernetes-cronhpa-controller:v1.4.0-a2f4954d-aliyun
  timezone: "Asia/Shanghai"

global:
  rbac:
    create: true
servicemonitor:
  enable: false
