cleanup:
  cleanupCustomResource: false

crds:
  needcreate: true

controller:
  image: registry.aliyuncs.com/acs/kubernetes-cronhpa-controller:v1.4.1-b8cd52c-aliyun
  timezone: "Asia/Shanghai"

global:
  rbac:
    create: true
servicemonitor:
  enable: false
