cleanup:
  cleanupCustomResource: false

crds:
  needcreate: true

controller:
  image: registry.aliyuncs.com/acs/kubernetes-cronhpa-controller:v1.4.0-b1bef851-aliyun
  timezone: "Asia/Shanghai"

global:
  rbac:
    create: true