name: kubernetes-cronhpa-controller
description: kubernetes-cronhpa-controller is a kubernetes cron horizontal pod autoscaler
  controller using crontab like scheme. You can use CronHorizontalPodAutoscaler with
  any kind object defined in kubernetes which support scale subresource(such as Deployment
  and StatefulSet).
apiVersion: v2
appVersion: 1.3.0
kubeVersion: ">=1.7.0-0"
keywords:
  - cronhpa
  - namespace:kube-system
  - releaseName:kubernetes-cronhpa-controller
  - category:autoscaling
home: https://github.com/AliyunContainerService/kubernetes-cronhpa-controller
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 2.x.x
version: 0.0.3
