# webhook admission controller
---
apiVersion: v1
kind: Service
metadata:
  name: kubernetes-cronhpa-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "fullname" . }}
    controller-tools.k8s.io: "1.0"
spec:
  selector:
    app: {{ template "fullname" . }}
    controller-tools.k8s.io: "1.0"
  ports:
  - name: metric
    port: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "fullname" . }}
    controller-tools.k8s.io: "1.0"
spec:
  replicas: {{ .Values.controller.replicas }}
  selector:
    matchLabels:
      app: {{ template "fullname" . }}
      controller-tools.k8s.io: "1.0"
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
        controller-tools.k8s.io: "1.0"
    spec:
      containers:
      - image: {{ .Values.controller.image }}
        command:
        - /bin/sh
        - '-c'
        - /root/kubernetes-cronhpa-controller --enableLeaderElection=true
        env:
        - name: TZ
          value: {{ .Values.controller.timezone }}
        imagePullPolicy: Always
        name: kubernetes-cronhpa-controller
        resources:
          {{- toYaml .Values.controller.resources | nindent 10 }}
      serviceAccount: kubernetes-cronhpa-controller
      {{- with .Values.controller.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.controller.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.controller.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.controller.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}


