# webhook admission controller
---
apiVersion: v1
kind: Service
metadata:
  name: kubernetes-cronhpa-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "fullname" . }}
    controller-tools.k8s.io: "1.0"
spec:
  selector:
    app: {{ template "fullname" . }}
    controller-tools.k8s.io: "1.0"
  ports:
  - name: metric
    port: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "fullname" . }}
    controller-tools.k8s.io: "1.0"
spec:
  selector:
    matchLabels:
      app: {{ template "fullname" . }}
      controller-tools.k8s.io: "1.0"
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
        controller-tools.k8s.io: "1.0"
    spec:
      containers:
      - image: {{ .Values.controller.image }}
        env:
        - name: TZ
          value: {{ .Values.controller.timezone }}
        imagePullPolicy: Always
        name: kubernetes-cronhpa-controller
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
      serviceAccount: kubernetes-cronhpa-controller