/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	"time"

	v1beta1 "github.com/AliyunContainerService/kubernetes-cronhpa-controller/pkg/apis/autoscaling/v1beta1"
	scheme "github.com/AliyunContainerService/kubernetes-cronhpa-controller/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// CronHorizontalPodAutoscalersGetter has a method to return a CronHorizontalPodAutoscalerInterface.
// A group's client should implement this interface.
type CronHorizontalPodAutoscalersGetter interface {
	CronHorizontalPodAutoscalers(namespace string) CronHorizontalPodAutoscalerInterface
}

// CronHorizontalPodAutoscalerInterface has methods to work with CronHorizontalPodAutoscaler resources.
type CronHorizontalPodAutoscalerInterface interface {
	Create(*v1beta1.CronHorizontalPodAutoscaler) (*v1beta1.CronHorizontalPodAutoscaler, error)
	Update(*v1beta1.CronHorizontalPodAutoscaler) (*v1beta1.CronHorizontalPodAutoscaler, error)
	UpdateStatus(*v1beta1.CronHorizontalPodAutoscaler) (*v1beta1.CronHorizontalPodAutoscaler, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1beta1.CronHorizontalPodAutoscaler, error)
	List(opts v1.ListOptions) (*v1beta1.CronHorizontalPodAutoscalerList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.CronHorizontalPodAutoscaler, err error)
	CronHorizontalPodAutoscalerExpansion
}

// cronHorizontalPodAutoscalers implements CronHorizontalPodAutoscalerInterface
type cronHorizontalPodAutoscalers struct {
	client rest.Interface
	ns     string
}

// newCronHorizontalPodAutoscalers returns a CronHorizontalPodAutoscalers
func newCronHorizontalPodAutoscalers(c *AutoscalingV1beta1Client, namespace string) *cronHorizontalPodAutoscalers {
	return &cronHorizontalPodAutoscalers{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the cronHorizontalPodAutoscaler, and returns the corresponding cronHorizontalPodAutoscaler object, and an error if there is any.
func (c *cronHorizontalPodAutoscalers) Get(name string, options v1.GetOptions) (result *v1beta1.CronHorizontalPodAutoscaler, err error) {
	result = &v1beta1.CronHorizontalPodAutoscaler{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("cronhorizontalpodautoscalers").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of CronHorizontalPodAutoscalers that match those selectors.
func (c *cronHorizontalPodAutoscalers) List(opts v1.ListOptions) (result *v1beta1.CronHorizontalPodAutoscalerList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1beta1.CronHorizontalPodAutoscalerList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("cronhorizontalpodautoscalers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested cronHorizontalPodAutoscalers.
func (c *cronHorizontalPodAutoscalers) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("cronhorizontalpodautoscalers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a cronHorizontalPodAutoscaler and creates it.  Returns the server's representation of the cronHorizontalPodAutoscaler, and an error, if there is any.
func (c *cronHorizontalPodAutoscalers) Create(cronHorizontalPodAutoscaler *v1beta1.CronHorizontalPodAutoscaler) (result *v1beta1.CronHorizontalPodAutoscaler, err error) {
	result = &v1beta1.CronHorizontalPodAutoscaler{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("cronhorizontalpodautoscalers").
		Body(cronHorizontalPodAutoscaler).
		Do().
		Into(result)
	return
}

// Update takes the representation of a cronHorizontalPodAutoscaler and updates it. Returns the server's representation of the cronHorizontalPodAutoscaler, and an error, if there is any.
func (c *cronHorizontalPodAutoscalers) Update(cronHorizontalPodAutoscaler *v1beta1.CronHorizontalPodAutoscaler) (result *v1beta1.CronHorizontalPodAutoscaler, err error) {
	result = &v1beta1.CronHorizontalPodAutoscaler{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("cronhorizontalpodautoscalers").
		Name(cronHorizontalPodAutoscaler.Name).
		Body(cronHorizontalPodAutoscaler).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *cronHorizontalPodAutoscalers) UpdateStatus(cronHorizontalPodAutoscaler *v1beta1.CronHorizontalPodAutoscaler) (result *v1beta1.CronHorizontalPodAutoscaler, err error) {
	result = &v1beta1.CronHorizontalPodAutoscaler{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("cronhorizontalpodautoscalers").
		Name(cronHorizontalPodAutoscaler.Name).
		SubResource("status").
		Body(cronHorizontalPodAutoscaler).
		Do().
		Into(result)
	return
}

// Delete takes name of the cronHorizontalPodAutoscaler and deletes it. Returns an error if one occurs.
func (c *cronHorizontalPodAutoscalers) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("cronhorizontalpodautoscalers").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *cronHorizontalPodAutoscalers) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("cronhorizontalpodautoscalers").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched cronHorizontalPodAutoscaler.
func (c *cronHorizontalPodAutoscalers) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.CronHorizontalPodAutoscaler, err error) {
	result = &v1beta1.CronHorizontalPodAutoscaler{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("cronhorizontalpodautoscalers").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
